export const authActionTypes = {
    LOGIN_REQUEST :"LOGIN_REQUEST",
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
}

export const categoryActionTypes = {
    GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE : 'GET_ALL_CATEGORIES_FAILURE',
    ADD_CATEGORY_REQUEST : 'ADD_CATEGORY_REQUEST',
    ADD_CATEOGRY_SUCCESS : 'ADD_CATEOGRY_SUCCESS',
    ADD_CATEGORY_FAILURE : 'ADD_CATEGORY_FAILURE',
}